baseURL = 'http://csrd.mistlyric.net/'
languageCode = 'en-us'
title = 'Cypher System Reference Document'
theme = 'hugo-book'

[languages.en]  
languageName = 'English'
contentDir = 'content.en'
weight = 1

# Theme
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com/Daegalus/csrd'
  BookCommitPath = 'commit'
  BookComments = false
  BookServiceWorker = true
  BookSection = "*"

[markup.goldmark.renderer]
  unsafe = true